In [1]:
import numpy as np

a. Compute the sum, mean, standard deviation, and variance of a two dimensional random integer array  along the second axis.

In [13]:
A = np.random.randint(1, 100, size=(3, 4))
print("Array:\n", A)

# along second axis (axis = 1 → row-wise)
print("Sum:", np.sum(A, axis=1))
print("Mean:", np.mean(A, axis=1))
print("Standard Deviation:", np.std(A, axis=1))
print("Variance:", np.var(A, axis=1))


Array:
 [[41 45 27 50]
 [70 41 92 91]
 [17 66 56 11]]
Sum: [163 294 150]
Mean: [40.75 73.5  37.5 ]
Standard Deviation: [ 8.55496932 20.71834936 23.85896058]
Variance: [ 73.1875 429.25   569.25  ]


    b. Get the indices of the sorted elements of a given array.
             B = [56, 48, 22, 41, 78, 91, 24, 46, 8, 33]

In [14]:
B = np.array([56, 48, 22, 41, 78, 91, 24, 46, 8, 33])

sorted_indices = np.argsort(B)

print("Original array:", B)
print("Indices of sorted elements:", sorted_indices)

Original array: [56 48 22 41 78 91 24 46  8 33]
Indices of sorted elements: [8 2 6 9 3 7 1 0 4 5]


In [ ]:
c. Create a 2-dimensional array of size m x n integer elements, also print the shape, type  and data type of the array and 
then reshape it into nx m array, n and m are user inputs given at the  run time.

In [5]:
m = int(input("Enter number of rows (m): "))
n = int(input("Enter number of columns (n): "))


arr = np.random.randint(1, 50, size=(m, n))

print("Array:\n", arr)
print("Shape:", arr.shape)
print("Type:", type(arr))
print("Data type:", arr.dtype)

reshaped = arr.reshape(n, m)
print("Reshaped array (n x m):\n", reshaped)


Enter number of rows (m):  3
Enter number of columns (n):  3


Array:
 [[31 11 43]
 [16 22 49]
 [ 7 40 42]]
Shape: (3, 3)
Type: <class 'numpy.ndarray'>
Data type: int32
Reshaped array (n x m):
 [[31 11 43]
 [16 22 49]
 [ 7 40 42]]


d. Test whether the elements of a given array are zero, non-zero
and NaN. Record  the indices of these elements in three separate arrays.

In [12]:
arr = np.array([0, 5, np.nan, 8, 0, 3, np.nan])
print ("array: \n" ,arr)

zero_indices = np.where(arr == 0)
nonzero_indices = np.where(arr != 0)
nan_indices = np.where(np.isnan(arr))

print("Zero indices:", zero_indices)
print("Non-zero indices:", nonzero_indices)
print("NaN indices:", nan_indices)


array: 
 [ 0.  5. nan  8.  0.  3. nan]
Zero indices: (array([0, 4]),)
Non-zero indices: (array([1, 2, 3, 5, 6]),)
NaN indices: (array([2, 6]),)
