In [32]:
import numpy as np

ques1:  Write a NumPy program to create an array of all the even integers from 30 to 70.

In [33]:
arr = np.arange(30, 71, 2)
arr

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

2.Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [34]:
arr2 = np.zeros((10, 10), dtype=int)

arr2[[0, -1], :] = 1
arr2[:, [0, -1]] = 1
arr2

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

3. Write a NumPy program to create a 5x10 matrix of distinct numbers from 1 to 50 and swap two columns in a 2d NumPy array.

In [35]:
import numpy as np

arr3 = np.arange(1, 51).reshape(5, 10)
print("original arr", arr3, "\n")
# swap column 1 and column 3
arr3[:, [1, 3]] = arr3[:, [3, 1]]

arr3

original arr [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]] 



array([[ 1,  4,  3,  2,  5,  6,  7,  8,  9, 10],
       [11, 14, 13, 12, 15, 16, 17, 18, 19, 20],
       [21, 24, 23, 22, 25, 26, 27, 28, 29, 30],
       [31, 34, 33, 32, 35, 36, 37, 38, 39, 40],
       [41, 44, 43, 42, 45, 46, 47, 48, 49, 50]])

4. Write a NumPy program to create a 5x10 matrix of distinct numbers from 1 to 50 and swap two rows in a 2d NumPy array.

In [36]:
arr4 = np.arange(1, 51).reshape(5, 10)
print("original arr", arr4, "\n")

# swap row 0 and row 4
arr4[[0, 4], :] = arr4[[4, 0], :]
arr4

original arr [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]] 



array([[41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

5. Add the two 2d NumPy arrays and modify the  resulting array by calculating the square root of each element

In [37]:
a = np.array([[1, 4], [9, 16]])
b = np.array([[4, 9], [16, 25]])

c = a + b
result = np.sqrt(c)
result

array([[2.23606798, 3.60555128],
       [5.        , 6.40312424]])

6. Retrieve indexes of only those elements where numbers are divisible by 3.

In [38]:

a = np.array([10, 15, 18, 22, 30, 41])

indexes = np.where(a % 3 == 0)

indexes

(array([1, 2, 4]),)

7. Create random vector of size 10 and replace the maximum value by 0

In [39]:
vec = np.random.randint(1, 50, 10)

vec[vec.argmax()] = 0
vec

array([29, 18, 40, 30, 27, 16, 22, 18, 10,  0], dtype=int32)

8. Create a random vector of size 10 and sort it

In [40]:

a = np.random.randint(1, 100, 10)

a_sorted = np.sort(a)
a_sorted

array([ 1,  3, 13, 47, 55, 59, 68, 78, 79, 81], dtype=int32)

9. Create a 10x10 array with random values and find the overall minimum and maximum values.

In [41]:
a = np.random.randint(0,100,(10, 10))

print("Minimum:", a.min())
print("Maximum:", a.max())

Minimum: 1
Maximum: 98


10. Create a 10x10 array with random values and find the minimum and maximum values, row-wise and column-wis

In [42]:
a = np.random.randint(0,100,(10, 10))

print("Row-wise minimum:", a.min(axis=1))
print("Row-wise maximum:", a.max(axis=1))

print("Column-wise minimum:", a.min(axis=0))
print("Column-wise maximum:", a.max(axis=0))

Row-wise minimum: [ 4 13  6  2 31  6  1  8  5 14]
Row-wise maximum: [99 99 92 74 70 95 93 93 79 91]
Column-wise minimum: [34  4  1 19  6  2  7 12 13 14]
Column-wise maximum: [95 77 73 99 77 93 99 81 93 93]
